language: d
d:
    - dmd
    - ldc

branches:
    only:
        - master
        - develop
        - travis-ci
        - /^v\d+\.\d+\.\d+(-\S+)?$/

script:
    - ./make-release.sh

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Arne Ludwig"
  - git config --local user.email "arne.ludwig@posteo.de"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(git rev-parse --abbrev-ref HEAD)-$(date +'%Y%m%dT%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
    provider: releases
    user: "arne.ludwig@posteo.de"
    password:
        secure: "v3zgAWzb1rIiBgQNGTu44nyN9qi8i6C1grmavVt4ozIqxcr9F6NmM5WC7dqKEpqmlI/Qs8i7cV/YKqD/SvDms+n5kAm4r3R4EQkrDlJM24vuQCKUunsEEubvFusEtY9dbgioUQrKahbARCCM2qF+ZzcQDpp47wK3CCGleHerjKr4hUw/ze6CGXKa4QpgFdB+LNP9saRPNQr6h2DAG69KR0+Iq15s8jdpqaFAyfjnWZ6SHKH1ULyVnDvBZL/R4c78uh6LOI3Hg/RvSqHIW+cPCQOld+/qk9roNBa9FicL+jMS06OsJadJZn+XPdIdnbNVbhzFnfBFcb0b03lCDT04FbkxnZJ63xM4TlRkebIeSVjs3zP6T4BNfPhQ9xOR4AKTgSlhH6aQC0H9Pr5+YAxtorBLOaYLk5XCjCVDr63lqBMUQdPGTArSbNkZiKR6MSeuoswL1UQuMU/TF7//Uc3OGzJBVJbybM7Z6ESjnfnF1+9QTxW+blCPhtY03SUPz+YDyKVPEhqg2LZypsK8sExV92CoQVbwG6ugKDQIFmMr/JUMpd5isVAMBE0xqigCg+5VrGDTnPItxTrQ7EYYMBbbtkeBbUPBLHA9daLbeY/tUOhZf4ectIqMLcho8M3+PxJdi+KrLU257sEWXoxx/MjsXH3XYS9f9+YOvhmHdVrY1+U="
    file: "dentist.*.tar.gz"
    skip_cleanup: true
    draft: true
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH = travis-ci || $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[^[:space:]]+)?$
