inputs:
    # The reference assembly where gaps should be closed
    reference:          reference.fasta
    # The set of long reads used for gap closing
    reads:              reads.fasta
    reads_type:         PACBIO_SMRT

outputs:
    # The gap-closed reference assembly
    output_assembly:    gap-closed.fasta

# This will be used to generate a config file for dentist. Vital parameters
# and options are automatically inserted by the workflow.
dentist_config:
    __default__:
        read-coverage:      73.0
        max-coverage-self:  3
        verbose:            2
    output:
        fasta-line-width:   80

additional_options:
    reference_dbsplit:
        - -x1000
        - -a
    reads_dbsplit:
        - -x1000
        - -a
    # Uncomment and adjust any of the following you need them

    # Improve alignment performance by masking low complexity regions
    # using DBdust
    #reference_dust: []

    # Alignment of the reference assembly against itself for repeat detection
    # using daligner
    #self_alignment: []

    # Alignment of the reference assembly against itself for tandem repeat
    # detection using datander
    #tandem_alignment: []

    # Tandem repeat detection using TANmask
    #tanmask: []

    # Alignment of the reads against the reference for identifying reads for
    # gap closing using damapper
    #ref_vs_reads_alignment: []

    # Improve alignment performance by masking low complexity regions
    # using DBdust
    #reads_dust: []

    # Alignment of the reads against themselves before building a consensus
    # using daligner
    #reads_vs_reads_alignment: []

    # Alignment of the consensus (sequence inserted into the gaps) against
    # the flanking contigs for validation and exact splicing using daligner
    #consensus_alignment: []

    # Options for building the consensus (sequence inserted into the gaps)
    # using daccord
    #consensus: []

# Directories for intermediate and log files.
workdir:            workdir
logdir:             logs

# Workflow files that are created inside of workdir
workflow:
    config:             dentist.json
    self_mask:          dentist-self
    reads_mask:         dentist-reads
    pile_ups:           pile-ups.db
    insertions_batch:   insertions/batch.{batch_id}.db
    insertions:         insertions.db

# Maximum number of threads to use
max_threads:        8

# Insertions are generated in batches of `batch_size`; use lower number to
# shorten the runtime of each job while increasing the number of jobs.
batch_size:         50
