inputs:
    # The reference assembly where gaps should be closed
    reference:          reference.fasta
    # The set of long reads used for gap closing
    reads:              reads.fasta
    reads_type:         PACBIO_SMRT

outputs:
    # The gap-closed reference assembly
    output_assembly:    gap-closed.fasta

# This will be used to generate a config file for dentist. Vital parameters
# and options are automatically inserted by the workflow.
dentist_config:
    __default__:
        read-coverage:      73.0
        max-coverage-self:  3
        verbose:            2
    output:
        fasta-line-width:   80

# Directories for intermediate and log files.
# NOTE: this is NOT `--workdir` of `dentist`
workdir:            workdir
logdir:             logs

# Workflow files that are created inside of workdir
workflow:
    config:             dentist.json
    self_mask:          dentist-self
    reads_mask:         dentist-reads
    pile_ups:           pile-ups.db
    insertions_batch:   insertions/batch.{batch_id}.db
    insertions:         insertions.db

# Maximum number of threads to use
max_threads:        8

# Insertions are generated in batches of `batch_size`; use lower number to
# shorten the runtime of each job while increasing the number of jobs.
batch_size:         50

# Limit the size of the k-mer index generated by `daligner`/`damapper`
dalign_flags:
    - -M25
    - -T{threads}

# Trim short contigs/reads from the input because they may be detrimental
dbsplit_flags:
    - -x1000 # trim contigs/reads with less than this number of bps
